### ISSUE TITLE
Compatability with ServerReplay

### ISSUE THREAD

**Issue by mcbianxiao** [sakura-ryoko/syncmatica#3]
I encountered the same problem when using `syncmatica-fabric-1.21-0.3.12-sakura.5` https://github.com/senseiwells/ServerReplay/issues/23 .
You can also look at the ServerReplay author's methods. See https://github.com/End-Tech/syncmatica/issues/74

**Comment by sakura-ryoko** [comment]
Why would this cause an issue with another mod ?  I don't technically understand the need for this.

**Comment by mcbianxiao** [comment]
In addition, both the Mod is installed on the 1.21 version of the server at the same time, also can cause IndexOutofBoundsException error. However, the server did not give any error.
I don't know what is the mod lead to this problem, so I also sent the message in https://github.com/senseiwells/ServerReplay/issues/23

**Comment by mcbianxiao** [comment]
After I applied the pull requests: https://github.com/sakura-ryoko/syncmatica/pull/4 , the problem seems to be solved

**Comment by sakura-ryoko** [comment]
Server Replay should not be doing anything with the Syncmatica Data Channel.  It should not even be listening for anything to do with it.

Perhaps it is a boundary that they shouldn't be crossing ?

**Comment by mcbianxiao** [comment]
I think so, too. I think it's weird. I'm sorry because I don't have the ability to determine exactly which mod is causing this problem
