### ISSUE TITLE
Hope to support Bukkit

### ISSUE THREAD

**Issue by fanlepian1** [sakura-ryoko/syncmatica#5]
Hope to support Bukkit
If you don't know how to use the bukkit API, you can learn from it

[bunnyi116/fabric-syncmatica](https://github.com/bunnyi116/fabric-syncmatica)
[bunnyi116/bukkit-syncmatica](https://github.com/bunnyi116/bukkit-syncmatica)

It adds plugin channels to fabric syncmatica, but it does not support the latest version of Minecraft
I hope you can add such a channel in your project to support bukkit, which is important to me
I have tried adding channels in the project you wrote before, but my technical skills were not very good, which resulted in me not being able to successfully complete such a function
If you see it, please reply to me. Thank you

**Comment by sakura-ryoko** [comment]
See the LeavesMC project, they do have some sort of Syncmatica support.

**Comment by fanlepian1** [comment]
Leaves uses the server, which is different from plugins
