### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by logitechno** [sakura-ryoko/syncmatica#8]
Is it possible to add Russian translation to this mod?

**Comment by sakura-ryoko** [comment]
Perhaps.  I have been doing Crowdin stuff.  If I do add additional languages though, the Quality will be questionable using Machine translations.

**Comment by sakura-ryoko** [comment]
I am currently doing the same for litematica / malilib itself.

**Comment by sakura-ryoko** [comment]
The Syncmatica lang file is quite small, but this is what Crowdin came up with:
https://github.com/sakura-ryoko/syncmatica/blob/1.21.3/src/main/resources/assets/syncmatica/lang/ru_ru.json

**Comment by logitechno** [comment]
Honestly, it looks like it was just thrown into the translator.

**Comment by sakura-ryoko** [comment]
> Honestly, it looks like it was just thrown into the translator.

That's exactly correct, as I do not speak russian, or other langs to be fair.

**Comment by sakura-ryoko** [comment]
So the way it works is if you have corrections, please let me know, and I'll correct it.

**Comment by logitechno** [comment]
I can send you my translation later.

**Comment by logitechno** [comment]
[ru_ru.json](https://github.com/user-attachments/files/17800740/ru_ru.json)

**Comment by sakura-ryoko** [comment]
In terms of accuracy, perhaps I can interest you in reviewing all of the masa mods ecosystem for russian ?
Such as:
https://github.com/sakura-ryoko/malilib/blob/pre-rewrite/fabric/DEV/src/main/resources/assets/malilib/lang/ru_ru.json
and
https://github.com/sakura-ryoko/litematica/blob/pre-rewrite/fabric/DEV/src/main/resources/assets/litematica/lang/ru_ru.json
.
There are WIP files I have for every mod if you want your mods translations to be more correct; just refer to the `DEV` branches.

**Comment by sakura-ryoko** [comment]
If any of these "Machine Translations" are bad (Even besides Russian) it's mainly due to a lack of having a native speaker of those languages review them.

**Comment by logitechno** [comment]
Might as well give it a try)

**Comment by sakura-ryoko** [comment]
Thank you.

**Comment by sakura-ryoko** [comment]
> Might as well give it a try)

And you can post up in those repo's of mine.
